import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Icon } from "@/components/icon";
import { CONTACT_EMAIL, SITE_LOCATION } from "@/lib/site";

export const metadata: Metadata = { title: "About", description: "Learn about Lakbay-Sinag Publishing and its work with Filipino educators, researchers, and writers.", alternates: { canonical: "/about" } };

const principles = [
  ["eye", "Our vision", "A publishing home where Filipino research, stories, and local knowledge can be discovered, cited, and carried forward with care."],
  ["users", "Our promise", "Clear standards and thoughtful editorial partnership throughout the publishing journey."],
  ["globe", "Our purpose", "Stronger recognition for educators, researchers, writers, and communities sharing work that matters."],
] as const;

export default function AboutPage() {
  return <main id="main-content" className="about-page about-page-v3">
    <section className="about-hero about-hero-v3"><Image className="about-hero-image object-cover" src="/assets/about-open-book-botanical.png" alt="An open book surrounded by leafy branches" fill priority sizes="100vw" /><div className="about-hero-shade" /><div className="section-shell about-hero-v3-inner"><div className="about-hero-v3-copy"><p className="about-kicker">About Lakbay-Sinag</p><h1>Publishing ideas <em>with purpose.</em></h1><p>Lakbay-Sinag helps educators and writers publish credible research and creative work for readers everywhere.</p><div className="about-hero-actions"><Link href="#our-story">Read our story <Icon name="arrow" className="h-4 w-4" /></Link><Link href="/submit">Submit your work <Icon name="arrow" className="h-4 w-4" /></Link></div></div></div></section>
    <nav className="about-section-nav" aria-label="About Lakbay-Sinag"><div className="section-shell"><a href="#our-story">Our story</a><a href="#our-purpose">Purpose and values</a><a href="#who-we-serve">Who we serve</a><a href="#contact">Contact</a></div></nav>
    <section className="about-identity-band"><div className="section-shell"><article><span><Icon name="sun" className="h-5 w-5" /></span><div><small>Our name</small><strong>Lakbay-Sinag means a journey guided by light.</strong></div></article><article><span><Icon name="book" className="h-5 w-5" /></span><div><small>Our archive</small><strong>Stable journal and publication records.</strong></div></article><article><span><Icon name="users" className="h-5 w-5" /></span><div><small>Who we serve</small><strong>Researchers, educators, writers, and communities.</strong></div></article><article><span><Icon name="shield" className="h-5 w-5" /></span><div><small>Our commitment</small><strong>Clear authorship, editorial care, and durable records.</strong></div></article></div></section>
    <section id="our-story" className="about-story-v3"><div className="section-shell"><header className="about-section-title"><p className="about-kicker">Our story</p><h2>Built to keep scholarship connected and discoverable.</h2><p>Lakbay-Sinag brings journals, studies, authors, citations, and DOI records together in a clear and accessible publishing platform.</p></header><div className="about-story-feature"><figure><Image src="/assets/services-fountain-pen-editorial.png" alt="A fountain pen resting beside manuscript pages" fill sizes="(max-width: 1000px) 100vw, 55vw" className="object-cover" /><figcaption><strong>Archive</strong><span>Research and creative work kept connected to its authors.</span></figcaption></figure><article><p>The platform responds to the real barriers educators, researchers, and writers face when sharing their work.</p><p><strong>Lakbay-Sinag</strong> provides safer submissions, clearer authorship, and stronger discovery for readers.</p><p>Publication pages preserve the supplied journal, citation, DOI, volume, issue, and authorship metadata so the scholarly record remains trustworthy.</p><Link href="/publications">Explore the publication archive <Icon name="arrow" className="h-4 w-4" /></Link></article></div></div></section>
    <section id="our-purpose" className="about-purpose-v3"><div className="section-shell"><header className="about-section-title"><p className="about-kicker">Our purpose</p><h2>Care, clarity, and reach guide the work.</h2><p>Our standards connect editorial quality with a publishing experience authors can understand and trust.</p></header><div className="about-principles-grid"><article className="about-principle-feature"><span><Icon name="eye" className="h-7 w-7" /></span><p>Our vision</p><h3>A publishing home where Filipino research, stories, and local knowledge can be discovered, cited, and carried forward with care.</h3></article>{principles.slice(1).map(([icon, label, copy]) => <article key={label}><span><Icon name={icon} className="h-6 w-6" /></span><div><p>{label}</p><h3>{copy}</h3></div></article>)}</div><div className="about-values-v3">{[["Care", "We treat manuscripts and personal information as private editorial material."], ["Clarity", "We make policies, status changes, citations, rights, and corrections understandable."], ["Reach", "We publish stable, searchable pages that connect authors with readers."], ["Integrity", "We preserve the record instead of silently rewriting publication history."], ["Stewardship", "We keep journal, study, author, citation, and DOI records complete and connected."]].map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section id="who-we-serve" className="about-audiences-v3"><div className="section-shell about-audiences-layout"><div className="about-audiences-copy"><p className="about-kicker">Who we serve</p><h2>Publishing support for every voice with work to share.</h2><p>Each collaboration begins with the needs of the work and the people responsible for it.</p><div className="about-audience-tabs" aria-label="Publishing audiences"><Link className="block rounded-xl border border-forest-900/15 px-4 py-3 font-bold text-forest-900" href="/journals">Researchers and educators</Link><Link className="block rounded-xl border border-forest-900/15 px-4 py-3 font-bold text-forest-900" href="/submit">Writers and contributors</Link><Link className="block rounded-xl border border-forest-900/15 px-4 py-3 font-bold text-forest-900" href="/services">Schools and institutions</Link></div></div><div className="about-audience-panels"><article><span><Icon name="users" className="h-7 w-7" /></span><p>For research, creativity, and community knowledge</p><h3>We help individuals and teams move from a clear manuscript to an accountable, discoverable publication record.</h3><Link href="/services">Explore publishing services <Icon name="arrow" className="h-4 w-4" /></Link></article></div></div></section>
    <section className="about-recognition-v3"><div className="section-shell"><article className="about-recognition-v3-card"><span><Icon name="book" className="h-9 w-9" /></span><div><p className="about-kicker !text-[#d9b57f]">The work ahead</p><h2>Accessible publishing, editorial quality, and meaningful support for authors.</h2><p>Our focus is practical: clear standards, safer tools, and a public record that makes each publication easier to find and cite.</p></div></article></div></section>
    <section id="contact" className="about-contact-v3"><div className="section-shell about-contact-v3-grid"><div><p className="about-kicker">Contact Lakbay-Sinag</p><h2>Start with the work you want readers to find.</h2><p>For a manuscript or publishing proposal, use the secure submission form. For a general question, email the editorial team.</p><div className="about-location-record"><span><Icon name="location" className="h-6 w-6" /></span><div><small>Serving</small><strong>{SITE_LOCATION}</strong><p>Working with authors, educators, and organisations across the Philippines and beyond.</p></div></div></div><div className="about-contact-links"><Link href="/submit"><Icon name="file" className="h-5 w-5" /><span><small>Secure submission</small><strong>Share a manuscript or proposal</strong></span><Icon name="arrow" className="h-4 w-4" /></Link><a href={`mailto:${CONTACT_EMAIL}`}><Icon name="mail" className="h-5 w-5" /><span><small>Editorial questions</small><strong>{CONTACT_EMAIL}</strong></span><Icon name="arrow" className="h-4 w-4" /></a></div></div></section>
  </main>;
}
