import type { Metadata } from "next";
import { Icon } from "@/components/icon";
import { PrivacyPreferences } from "@/components/privacy-preferences";
import { ANALYTICS_ENABLED, CONTACT_EMAIL, LEGAL_EFFECTIVE_DATE, SITE_NAME } from "@/lib/site";

export const metadata: Metadata = { title: "Privacy notice", description: `How ${SITE_NAME} collects, uses, stores, protects, and deletes personal information and editorial files.`, alternates: { canonical: "/privacy" } };

const disclosures = [
  ["users", "Information you provide", "Names, email addresses, credentials, affiliations, ORCID records, correspondence, and other details entered in submission or contact forms."],
  ["file", "Editorial materials", "Manuscripts, author photographs, payment proof, special instructions, revision files, and records created while evaluating or preparing work."],
  ["search", "Technical and analytics data", ANALYTICS_ENABLED ? "With consent, general pageviews, traffic sources, search behavior, browser type, referring page, and similar usage information. Essential security and anti-abuse information may be processed without optional analytics." : "Optional analytics are currently disabled. Essential technical, security, and anti-abuse information may still be processed to operate and protect the service."],
  ["shield", "Retention and deletion", "Records are kept only as long as reasonably necessary for publishing services, editorial integrity, contractual requirements, security, or legal obligations."],
] as const;

export default function PrivacyPage() {
  return <main id="main-content" className="privacy-page">
    <section className="privacy-hero"><div className="privacy-grain" aria-hidden="true" /><div className="section-shell privacy-hero-grid"><div className="privacy-hero-copy"><div className="eyebrow page-eyebrow"><span><Icon name="lock" className="h-4 w-4" /></span>Legal and privacy</div><h1>Privacy should be<br /><em>understood</em>, not buried.</h1><p>This notice explains the production data flow used by {SITE_NAME} and the choices available to readers and authors.</p><div className="privacy-hero-actions"><a href="#privacyNotice">Read the full notice <Icon name="arrow" className="h-4 w-4" /></a><a href={`mailto:${CONTACT_EMAIL}`}>Contact privacy <Icon name="mail" className="h-4 w-4" /></a></div></div><aside className="privacy-seal"><span><Icon name="shield" className="h-9 w-9" /></span><p>Effective date</p><strong>{LEGAL_EFFECTIVE_DATE}</strong><small>Applies to this website, secure submissions, newsletters, and editorial administration.</small></aside></div></section>
    <section className="privacy-principles"><div className="section-shell privacy-principle-grid">{[["eye", "Clear purpose", "We explain why information is needed."], ["lock", "Restricted access", "Editorial information is handled as private material."], ["shield", "Meaningful control", ANALYTICS_ENABLED ? "Optional analytics depend on your choice." : "Optional analytics are currently disabled."], ["file", "Limited retention", "Records are kept only as long as necessary."]].map(([icon, title, copy]) => <article key={title}><span><Icon name={icon as "eye" | "lock" | "shield" | "file"} className="h-5 w-5" /></span><div><strong>{title}</strong><p>{copy}</p></div></article>)}</div></section>
    <section id="privacyNotice" className="privacy-notice"><div className="section-shell privacy-layout">
      <aside className="privacy-contents"><p>In this notice</p><nav aria-label="Privacy notice sections"><a className="block rounded-xl px-3 py-2 text-sm font-bold hover:bg-forest-800 hover:text-white" href="#information">Information</a><a className="block rounded-xl px-3 py-2 text-sm font-bold hover:bg-forest-800 hover:text-white" href="#use">Use and storage</a><a className="block rounded-xl px-3 py-2 text-sm font-bold hover:bg-forest-800 hover:text-white" href="#rights">Your choices</a><a className="block rounded-xl px-3 py-2 text-sm font-bold hover:bg-forest-800 hover:text-white" href="#privacyPreferences">Preferences</a></nav><div><Icon name="lock" className="h-4 w-4" /><p>Do not email passwords or unnecessary sensitive documents. Use the secure submission form for editorial files.</p></div></aside>
      <div className="privacy-main">
        <section id="information" className="privacy-section"><header className="privacy-section-heading"><p>What we collect</p><h2>Information enters the editorial record for a clear reason.</h2><span>We collect only the information needed to operate the website, manage a submission, prepare a publication, or meet a security, contractual, integrity, or legal obligation.</span></header><div className="privacy-disclosures">{disclosures.map(([icon, title, copy], index) => <details key={title} open={index === 0}><summary><span><Icon name={icon} className="h-5 w-5" /></span><strong>{title}</strong><Icon name="chevron" className="h-4 w-4" /></summary><div><p>{copy}</p></div></details>)}</div></section>
        <section id="use" className="privacy-section"><header className="privacy-section-heading"><p>Use and storage</p><h2>Private editorial materials stay private.</h2><span>Information is used to assess submissions, communicate with authors, prepare publications, maintain the scholarly and contractual record, prevent misuse, and operate the service. {SITE_NAME} does not sell personal information.</span></header><div className="privacy-journey"><article><span><Icon name="shield" className="h-6 w-6" /></span><p>Submission files are uploaded directly to a private Supabase Storage bucket. Public users cannot list or retrieve them.</p><strong>Authorized administrators authenticate through Supabase and receive short-lived signed links only when a file is needed. Vercel hosts the website and server routes; public publication files are handled separately from private submission files.</strong></article></div></section>
        <section id="rights" className="privacy-section privacy-rights"><header className="privacy-section-heading"><p>Your choices</p><h2>Ask us to review eligible personal information.</h2><span>You may request access, correction, or deletion where appropriate. Some records may need to remain to preserve the scholarly record or meet contractual, security, fraud-prevention, or legal obligations.</span></header><div>{[["01", "Access your information", `Ask what eligible personal information ${SITE_NAME} holds and how it is being used.`], ["02", "Correct inaccurate details", "Request corrections to eligible contact, contributor, or account information."], ["03", "Request deletion", "Ask for deletion of eligible information, subject to necessary retention obligations."], ["04", ANALYTICS_ENABLED ? "Change analytics consent" : "Review analytics status", ANALYTICS_ENABLED ? "Allow or decline optional analytics at any time using the controls below." : "Optional analytics are currently disabled; the status below will change if analytics are configured later."]].map(([number, title, copy]) => <article key={title}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div><Icon name="arrow" className="h-4 w-4" /></article>)}</div></section>
        <PrivacyPreferences />
        <section className="privacy-contact"><span><Icon name="mail" className="h-6 w-6" /></span><div><p>Contact</p><h2>Questions about privacy or your data?</h2><span>Include a relevant submission reference or publication URL so the team can locate the right record.</span></div><a href={`mailto:${CONTACT_EMAIL}`}>Email privacy <Icon name="arrow" className="h-4 w-4" /></a></section>
      </div>
    </div></section>
  </main>;
}
