import Image from "next/image";
import Link from "next/link";
import { HomeFaq } from "@/components/home-faq";
import { HomeNewsletter } from "@/components/home-newsletter";
import { HomePublications } from "@/components/home-publications";
import { HomeTestimonials } from "@/components/home-testimonials";
import { Icon } from "@/components/icon";
import { FlipWords } from "@/components/ui/flip-words";
import { getCurrentIssueForJournal, getHomePublications, getJournals, getPublicContentCounts } from "@/lib/content";
import { archiveIssueLabel, getJournalPresentation } from "@/lib/journal-presentation";
import { SITE_NAME, SITE_SHORT_NAME } from "@/lib/site";

export const revalidate = 300;

const topics = [["Education","book"],["STEM","layers"],["Social science","users"],["Poetry","edit"],["Fiction","book"],["Creative nonfiction","edit"],["Culture","shield"],["Technology","layers"],["Community","users"],["Science writing","search"],["Filipino identity","globe"],["Teaching practice","edit"]] as const;
const services = [["edit","Editorial development","Structural editing, copyediting, proofreading, and author guidance for research and creative manuscripts."],["book","Book & journal design","Reader-centered interior layouts, cover systems, digital editions, and accessible publication templates."],["lock","Copyright support","Practical assistance for permissions, attribution, ISBN preparation, and intellectual-property documentation."],["globe","Digital publishing","Searchable, responsive publication pages with metadata, DOI-ready records, and long-term discoverability."]] as const;
const journalColors = ["from-emerald-900 via-emerald-700 to-amber-600","from-rose-950 via-rose-700 to-orange-500","from-violet-950 via-violet-700 to-amber-500"];

export default async function HomePage() {
  const [publishedJournals, publications, counts] = await Promise.all([getJournals(), getHomePublications(), getPublicContentCounts()]);
  const journalCards = publishedJournals.slice(0, 3).map((journal) => {
    const presentation = getJournalPresentation(journal);
    const records = publications.filter((publication) => publication.journal.id === journal.id);
    const cur = getCurrentIssueForJournal(journal.id);
    return { ...journal, type: presentation.type, cadence: presentation.cadence, issue: cur ? "Vol. " + cur.volume + ", No. " + cur.issue : archiveIssueLabel(records[0]) };
  });
  return <main id="main-content">
    <section className="hero home-hero flex items-center">
      <Image src="/assets/home-eagle-researcher-3d.webp" alt="Illustrated Philippine eagle researcher studying botanical specimens in a warm library" className="hero-background" width={1680} height={945} sizes="100vw" fetchPriority="high" priority/>
      <div className="hero-gradient" aria-hidden="true"/>
      <div className="section-shell hero-content"><div className="max-w-[610px]"><p className="eyebrow">Research · Articles · Poetry · Books</p><h1 className="display-title mt-4 font-normal text-5xl sm:text-6xl lg:text-[4.5rem]"><span className="block">Ideas deserve</span><span className="block whitespace-nowrap">to be <FlipWords words={["written.","refined.","published.","remembered."]} className="title-emphasis-flip px-0"/></span></h1><p className="mt-5 max-w-xl text-base leading-8 md:text-lg">{SITE_NAME} gives educators, researchers, poets, and storytellers an accessible, credible home for work that matters.</p>
        <Link href="/search" className="search-button hero-search mt-8 flex w-full max-w-xl items-center gap-3 rounded-2xl border border-forest-900/10 p-3 text-left hover:border-clay-500"><Icon name="search" className="h-5 w-5 text-forest-700"/><span className="flex-1 text-sm text-gray-600">Search articles, authors, topics, or journals…</span><kbd className="search-key hidden rounded-md border border-gray-200 bg-white px-2 py-1 text-[.68rem] font-semibold text-gray-400 sm:block">Ctrl K</kbd></Link>
        <div className="hero-actions mt-6 flex flex-wrap gap-3"><Link href="/journals" className="inline-flex items-center gap-2 rounded-full bg-forest-800 px-5 py-3 text-sm font-bold text-white hover:bg-forest-900">Explore journals <Icon name="arrow" className="h-4 w-4"/></Link><Link href="/submit" className="inline-flex items-center gap-2 rounded-full bg-white/90 px-5 py-3 text-sm font-bold text-forest-900">Submit your work <Icon name="arrow" className="h-4 w-4"/></Link></div>
        <div className="hero-trust"><div><span><Icon name="book"/></span><p><strong>Trusted platform</strong><small>Editorial standards you can rely on.</small></p></div><div><span><Icon name="users"/></span><p><strong>For every voice</strong><small>From classrooms to communities.</small></p></div><div><span><Icon name="feather"/></span><p><strong>Impact that lasts</strong><small>Ideas today, change tomorrow.</small></p></div></div></div><aside className="hero-quote"><b>“</b><p>Every story adds to our collective understanding of who we are.</p><span>— {SITE_NAME}</span></aside></div>
    </section>

    <section className="hero-stats" data-reveal><div className="section-shell hero-stats-grid">{[["book",String(publishedJournals.length),"Editorial journals","Quality publications across disciplines."],["file",counts.publications.toLocaleString("en-US"),"Published works","Research, articles, poetry, and books."],["users",counts.authors.toLocaleString("en-US"),"Contributors","Educators, researchers, and writers."],["globe","", "Publish Without Borders","Connecting Filipino and international authors with a wider academic and literary audience."]].map(([icon,value,label,copy])=><div className={`hero-stat ${!value ? "hero-stat-message" : ""}`} key={label}><span><Icon name={icon as "book"|"file"|"users"|"globe"} className="h-6 w-6"/></span><p>{value && <strong>{value}</strong>}<b>{label}</b><small>{copy}</small></p></div>)}</div></section>

    <section className="section-shell py-20" data-reveal><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">New &amp; noteworthy</p><h2 className="display-title mt-3 text-4xl font-bold text-forest-900">Stories shaping the conversation</h2></div><Link href="/publications" className="flex items-center gap-2 text-sm font-bold text-clay-700">Browse all publications <Icon name="arrow" className="h-4 w-4"/></Link></div><div className="mt-8"><HomePublications publications={publications.slice(0,24)}/></div></section>

    <section className="home-journals" id="journals" data-reveal><div className="journal-atmosphere" aria-hidden="true"><span/><span/><span/></div><div className="section-shell journal-section-inner"><div className="journal-section-heading"><p className="eyebrow">Our journals</p><h2 className="display-title"><em className="title-emphasis title-emphasis-distinct">Distinct</em>{" "}homes{" "}<br/>for meaningful work</h2><p>Each published journal can define its own scope and editorial identity while sharing a commitment to clarity, inclusion, and quality.</p></div><div className="journal-home-grid">{journalCards.map((journal,index)=><article key={journal.id} className="journal-card home-journal-card overflow-hidden rounded-2xl border border-forest-900/10 bg-white"><Link href={`/journals/${journal.slug}`} className={`cover ${journalColors[index % journalColors.length]} flex flex-col justify-between p-7`}><div className="cover-lines"/><div><p className="text-[.68rem] font-bold uppercase tracking-[.18em] opacity-80">{SITE_SHORT_NAME} Journal</p><h3 className="mt-5 max-w-[13rem] font-serif text-3xl font-bold leading-tight">{journal.title}</h3></div><div><p className="text-xs font-medium opacity-75">{journal.issue}</p><p className="mt-1 text-sm font-semibold">{journal.type}</p></div></Link><div className="journal-card-body p-6"><p>{journal.description}</p><div className="journal-card-footer"><span>{journal.cadence}</span><Link href={`/journals/${journal.slug}`}>Explore journal <Icon name="arrow" className="h-4 w-4"/></Link></div></div></article>)}{!journalCards.length && <p className="journal-empty-state">Journal programmes will appear after the second branch publishes its replacement records.</p>}</div><div className="journal-commitment"><span>{publishedJournals.length} published {publishedJournals.length === 1 ? "journal" : "journals"}</span><i aria-hidden="true"/><strong>One commitment to clarity, inclusion, and quality.</strong></div></div></section>

    <section className="home-topics" id="topics" data-reveal><div className="section-shell"><div className="topics-heading"><div className="topics-intro"><p className="eyebrow">Explore by topic</p><h2 className="display-title"><em className="title-emphasis title-emphasis-follow">Follow</em> what moves your mind<span>.</span></h2><p>Discover rigorous research, lived experience, and creative work across disciplines and forms.</p></div></div><div className="topics-content"><div className="topic-card-grid">{topics.map(([topic,icon],index)=><Link href={`/search?q=${encodeURIComponent(topic)}`} key={topic} className={`topic-card topic-tone-${index%3}`}><span><Icon name={icon}/></span><strong>{topic}</strong></Link>)}</div><aside className="topic-search-callout"><div className="topic-search-mark"><Icon name="search" className="h-8 w-8"/></div><div className="topic-search-copy"><p className="eyebrow">Start with a question</p><h3>Find the work that speaks to you.</h3><p>Search by journal, topic, author, or year, then follow the threads that matter.</p><div className="topic-search-filters" aria-hidden="true"><span>Journals</span><span>Topics</span><span>Authors</span><span>Years</span></div></div><Link href="/search" className="topic-search-action"><span>Explore the archive</span><Icon name="arrow" className="h-4 w-4"/></Link></aside></div></div></section>

    <section className="home-services" data-reveal><div className="section-shell services-layout"><div className="services-feature"><div className="eyebrow"><Icon name="shield" className="h-5 w-5"/> For authors &amp; institutions</div><h2 aria-label="Publishing should feel clear, not closed."><span aria-hidden="true">Publishing should<br/>feel <em className="title-emphasis title-emphasis-clear">clear</em>, not closed.</span></h2><i/><p>We combine editorial care, thoughtful design, copyright guidance, and digital distribution in one accessible process.</p><div className="services-values">{[["users","Author-first support"],["shield","Quality & integrity"],["globe","Global visibility"],["book","Lasting impact"]].map(([icon,label])=><div key={label}><span><Icon name={icon as "users"|"shield"|"globe"|"book"}/></span><strong>{label}</strong></div>)}</div><Link href="/editorial-standards">View editorial guidelines <Icon name="arrow" className="h-5 w-5"/></Link></div><div className="services-card-grid">{services.map(([icon,title,copy])=><article className="service-card premium-service-card" key={title}><span><Icon name={icon}/></span><h3>{title}</h3><i/><p>{copy}</p><Link href="/services">Learn about {title.toLocaleLowerCase()} <Icon name="arrow" className="h-4 w-4"/></Link></article>)}</div></div></section>

    <section id="testimonials" className="home-testimonials" aria-label="Reader and contributor testimonials" data-reveal><div className="home-testimonials-orbit" aria-hidden="true"/><HomeTestimonials/></section>

    <section className="quote-panel dispatch-panel motif" data-reveal><div className="section-shell grid gap-8 py-14 md:grid-cols-[1fr_.9fr] md:items-center"><div><p className="eyebrow">{SITE_SHORT_NAME} Dispatch</p><h2 className="mt-3 font-serif text-3xl font-bold md:text-4xl">Good writing, thoughtfully selected.</h2><p className="mt-3 max-w-xl text-sm leading-7">The second branch can connect a verified double-opt-in newsletter before launch.</p></div><HomeNewsletter/></div></section>

    <section className="home-faq-section" data-reveal><div className="section-shell home-faq-layout"><div className="home-faq-intro"><p className="eyebrow">Frequently asked</p><span className="home-faq-count" aria-hidden="true">04</span><h2 className="display-title">Before you send your work<span>.</span></h2><p>Clear answers about submissions, review, fees, rights, and publishing timelines.</p><div className="home-faq-intro-rule" aria-hidden="true"/><Link href="/faq">View all questions <Icon name="arrow" className="h-4 w-4"/></Link></div><div className="home-faq-answers"><p className="home-faq-answers-label">Start with the essentials</p><HomeFaq/></div></div></section>
  </main>;
}
