import type { Metadata } from "next";
import Link from "next/link";
import { Icon } from "@/components/icon";
import { getAuthors, getJournals, searchArchive } from "@/lib/content";
import { SITE_NAME, SITE_SHORT_NAME } from "@/lib/site";

export const metadata: Metadata = { title: "Search", description: `Search the ${SITE_NAME} publication archive by title, author, journal, DOI, or keyword.`, robots: { index: false, follow: true } };

function year(value: string) { return value.slice(0, 4); }
function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }

export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const query = (await searchParams).q?.trim() || "";
  const [results, journals, authors] = await Promise.all([query ? searchArchive(query) : Promise.resolve([]), getJournals(), getAuthors()]);
  return <main id="main-content"><section className="listing-hero border-b border-forest-900/10 bg-white"><div className="section-shell py-16"><p className="eyebrow">Discovery</p><h1 className="display-title mt-3 max-w-4xl text-5xl font-bold text-forest-900">Search the {SITE_SHORT_NAME} archive.</h1><p className="mt-4 max-w-2xl leading-8 text-gray-600">Find publications by title, author, journal, keyword, or DOI.</p><form className="mt-8 grid max-w-3xl grid-cols-[minmax(0,1fr)_auto] overflow-hidden rounded-xl border border-forest-900/15 bg-parchment" role="search"><label htmlFor="searchQuery" className="sr-only">Search query</label><div className="flex min-w-0 items-center gap-3 px-4"><Icon name="search" className="h-5 w-5 shrink-0 text-forest-700" /><input id="searchQuery" name="q" type="search" defaultValue={query} autoFocus placeholder="Title, author, DOI, journal, or keyword" className="min-w-0 flex-1 bg-transparent py-4 outline-none" /></div><button className="bg-forest-800 px-6 text-sm font-bold text-white">Search</button></form></div></section>
    <section className="section-shell py-14"><div className="search-section-heading"><div><p>Publication archive</p><h2>{query ? "Matching publications" : "Start with a search"}</h2></div><span>{query ? results.length : "—"}</span></div>{query ? results.length ? <div className="search-results-grid">{results.map((publication) => <article key={publication.id} className="search-result-card"><div className="search-result-heading"><span className="search-result-topic">{publication.contentType === "research" ? "Research" : publication.contentType === "creative" ? "Creative work" : "Commentary"}</span><div><Link href={`/journals/${publication.journal.slug}`}>{publication.journal.title}</Link></div></div><h2><Link href={`/publications/${publication.slug}`}>{publication.title}</Link></h2><p className="search-result-abstract">{publication.abstract || "This historical record is preserved with its journal, authorship, and citation details."}</p><div className="search-result-record"><p className="search-result-byline"><span>{publication.authorDisplay}</span><time dateTime={publication.publicationDate}>{year(publication.publicationDate)}</time></p>{publication.doi && <span className="search-result-doi">DOI {publication.doi}</span>}<div className="search-result-actions"><Link href={`/publications/${publication.slug}`}>View publication <Icon name="arrow" className="h-3.5 w-3.5" /></Link><span>{publication.volume ? `Vol. ${publication.volume}` : "Publication record"}</span></div></div></article>)}</div> : <div className="rounded-2xl border border-dashed border-forest-900/20 bg-white p-8"><h2 className="font-serif text-2xl font-bold text-forest-900">No matching publication</h2><p className="mt-3 text-gray-600">Try an author surname, DOI, journal title, keyword, or shorter phrase.</p></div> : <div className="rounded-2xl border border-forest-900/10 bg-[#f5f7f4] p-8"><h2 className="font-serif text-2xl font-bold text-forest-900">Search the connected archive</h2><p className="mt-3 max-w-xl text-gray-600">Use the search field above to look across titles, abstracts, author names, journals, keywords, and DOI records.</p></div>}</section>
    <section className="search-directory-band"><div className="section-shell py-14"><div className="search-section-heading"><div><p>Journal directory</p><h2>Choose a publishing programme</h2></div><span>{journals.length}</span></div><div className="search-journals-grid">{journals.map((journal) => <article key={journal.id} className="search-journal-card"><div><span>{journal.scope || "Publishing programme"}</span><h3><Link href={`/journals/${journal.slug}`}>{journal.title}</Link></h3><p>{journal.description}</p></div><dl><div><dt>ISSN</dt><dd>{journal.issn || "Not listed"}</dd></div><div><dt>Focus</dt><dd>{journal.scope || "Editorial programme"}</dd></div></dl><Link className="search-panel-link" href={`/journals/${journal.slug}`}>Explore journal <Icon name="arrow" className="h-3.5 w-3.5" /></Link></article>)}</div></div></section>
    <section className="section-shell py-14"><div className="search-section-heading"><div><p>Contributor directory</p><h2>Meet the authors</h2></div><span>{authors.length}</span></div><div className="search-authors-grid">{authors.slice(0, 6).map((author) => <article key={author.id} className="search-author-card"><span className="search-author-initials">{initials(author.name)}</span><div><h3><Link href={`/authors/${author.slug}`}>{author.name}</Link></h3><p>{author.affiliation || author.credentials || "Contributor profile"}</p></div><span className="search-author-count"><strong>Profile</strong><span>View record</span></span><Link className="search-author-link" href={`/authors/${author.slug}`} aria-label={`View ${author.name}'s profile`}><Icon name="arrow" className="h-3.5 w-3.5" /></Link></article>)}</div><Link className="search-panel-link mt-6" href="/authors">Browse all contributors <Icon name="arrow" className="h-3.5 w-3.5" /></Link></section>
  </main>;
}
